[phases.setup]
nixPkgs = ['php', 'php82Extensions.gd', 'php82Extensions.mbstring', 'php82Extensions.pdo_mysql', 'php82Extensions.zip']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
composer install --no-dev --optimize-autoloader && php artisan migrate --force && php artisan storage:link --force

[start]
php artisan migrate --force && php artisan storage:link --force && php -S 0.0.0.0:$PORT -t public